### ISSUE TITLE
Could not load file or assembly Interop.NetFwTypeLib

### ISSUE THREAD

**Issue by Serg046** [falahati/WindowsFirewallHelper#1]
I just tried the sample and got the exceptions.
Looks like the same issue as described here [stackoverflow](https://stackoverflow.com/questions/4296240/deploying-netfwtypelib-to-manage-the-windows-firewall)

```
var rule = FirewallManager.Instance.CreateApplicationRule(
FirewallManager.Instance.GetProfile().Type, @"MyApp Rule", 
FirewallAction.Allow, @"C:\MyApp.exe");
```

**Comment by falahati** [comment]
Hi, Please update the issue with your Windows version and build configuration.

Thanks

**Comment by TechnikEmpire** [comment]
Same issue Win 10 x64 1703 Visual Studio 2015 WPF application targeting .NET 4.5.2.

**Comment by TechnikEmpire** [comment]
Same issue Win 10 x64 1703 Visual Studio 2015 WPF application targeting .NET 4.5.2.

**Comment by TechnikEmpire** [comment]
The following post build command will correctly copy the interop library to the target directory:

`xcopy /Y "$(ProjectDir)obj\$(PlatformName)\$(Configuration)\Interop.NetFwTypeLib.dll" "$(TargetDir)"`

Without this, the interop library is stuck in the intermediates directory.

**Comment by falahati** [comment]
It seems that simply removing the "Interop.NetFwTypeLib.dll" from references solves the problem. I will update the NuGet package as soon as possible to solve this problem.

**Comment by falahati** [comment]
This should be fixed now with the latest NuGet release.

**Comment by TechnikEmpire** [comment]
@falahati thanks for your response on both tickets! Will update nuget and check latest version out today.
