### ISSUE TITLE
Very slow ActiveCollection<T>.Sync

### ISSUE THREAD

**Issue by nickguletskii** [falahati/WindowsFirewallHelper#10]
`ActiveCollection<T>.Sync` is very inefficient and causes significant slowdowns. Getting rules takes tens of seconds when there are about 1000 firewall rules.

I implemented my own replacement using LINQ, but it seems like this library targets .NET 2.0, so I can't upstream the change. Is there any particular reason for that?

**Comment by falahati** [comment]
Compatibility actually. Can I see your fork and the changes you made? I might be able to optimize it based on your code.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nickguletskii** [comment]
Sure, here it is: https://github.com/nickguletskii/WindowsFirewallHelper

In particular, this is the commit: https://github.com/nickguletskii/WindowsFirewallHelper/commit/1181b7bea4a37508feee3d8fe9f3077ebe80f79e

.NET 2.0 doesn't have sets, so to optimize this method you would have to implement one yourself.

**Comment by falahati** [comment]
Updated to Net3.5 and now uses Linq for this part of the code and couple of other places as well as using a hash code dictionary to decrease the number of calls to the native COM side. Therefore the code should be significantly faster.
Please consider reopening this issue if you had any further problem with this or if the changes broke something.
