### ISSUE TITLE
Problem setting LocalPorts / RemotePorts [Help Wanted]

### ISSUE THREAD

**Issue by sscotter** [falahati/WindowsFirewallHelper#11]
' 1st Test Case
Dim Rule As IRule = FirewallManager.Instance.CreateApplicationRule(FirewallManager.Instance.GetProfile().Type, "Test Name", FirewallAction.Allow, "MyApp.exe")
Rule.Direction = FirewallDirection.Inbound
Rule.RemoteAddresses = {WindowsFirewallHelper.Addresses.SingleIP.Parse("192.168.0.1)}

**Rule.LocalPorts = {CUShort(10050)}** _'Test 1_
**Rule.RemotePorts = {CUShort(10050)}** _'Test 2_

' 2nd Test Case
Dim AllRulesTest = FirewallManager.Instance.Rules

For Each SingelRuleTest As IRule In AllRulesTest
	If SingelRuleTest.LocalPorts.Length > 0 Then
		Console.WriteLine("{0}, {1}, {2}", SingelRuleTest.Name, SingelRuleTest.LocalPorts, SingelRuleTest.Profiles.ToString(), SingelRuleTest.RemoteAddresses.ToString)
		**Rule.LocalPorts = SingelRuleTest.LocalPorts** _'Test 3 - You'd think this would work as its taking a copy of LocalPorts from an existing rule._
	End If

Next

All attempts to set LocalPorts or RemotePorts results in an exception "Value does not fall within the expected range."

Any advice gratefully received.

**Comment by sscotter** [comment]
Just thought maybe the LocalPorts/RemotePorts can only be set using the CreatePortRule method but even that results in the "Value does not fall within the expected range." exception.

Dim TesingPortRule As IRule = FirewallManager.Instance.CreatePortRule(FirewallManager.Instance.GetProfile().Type, "Test2", FirewallAction.Allow, CUShort(10050))

**Comment by falahati** [comment]
Hey,

Port number is only valid for UDP and TCP rules. Try setting the `Protocol` to TCP or UDP before setting the port. I will try to add a more descriptive exception there.

```VB
Rule.Protocol = FirewallProtocol.TCP
```

**Comment by falahati** [comment]
The problem with the `FirewallManager.Instance.CreatePortRule` method is a bug tho. Will fix and release a new version ASAP.

**Comment by sscotter** [comment]
Spot on, the following code works perfectly.

Dim Rule As IRule = FirewallManager.Instance.CreateApplicationRule(FirewallManager.Instance.GetProfile().Type, RuleName, FirewallAction.Allow, ZabbixAgentPath)
Rule.Direction = FirewallDirection.Inbound
Rule.RemoteAddresses = {WindowsFirewallHelper.Addresses.SingleIP.Parse(ZabbixServerList.ServerActive)}
Rule.Protocol = FirewallProtocol.TCP
Rule.LocalPorts = {CUShort(10050)}

FirewallManager.Instance.Rules.Add(Rule)

Thanks
