### ISSUE TITLE
CS0246 - The type or namespace name 'INetFwRule3' could not be found 

### ISSUE THREAD

**Issue by DavidXanatos** [falahati/WindowsFirewallHelper#14]
I tried to build this library using visual studio 2015 and 2017 but in booth cases i get an error it seams INetFwRule3 is unknown.
How can I fix the issue?

**Comment by icnocop** [comment]
Which operating system are you building on?

I think you need to be running Windows 8 or higher.

I'm building on Windows 10 without issues.

For reference, the requirements for [INetFwRule3](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/netfw/nn-netfw-inetfwrule3#requirements) indicates Windows 8 and Windows Server 2012.

**Comment by brent-williams** [comment]
Nice one @icnocop, `INetFwRule3` build failure on Windows 7 resolved for me by building on a Windows 10 box.
