### ISSUE TITLE
Wrong condition when checking if port in FirewallAPIv2 is UDP

### ISSUE THREAD

**Issue by jfevia** [falahati/WindowsFirewallHelper#19]
https://github.com/falahati/WindowsFirewallHelper/blob/e17c78a84130f6f5c1c5a3c0a4d3fe712a597965/WindowsFirewallHelper/FirewallAPIv2/Firewall.cs#L137

This condition throws an exception if the protocol is **not TCP** and **is UDP**.

I believe the right condition is **not TCP and not UDP**.

**Comment by falahati** [comment]
True, thanks for reporting this. It seems that I missed a `!` there.

**Comment by falahati** [comment]
Should be fixed with the latest release.
