### ISSUE TITLE
[Question] Where does "Interop.NetFwTypeLib.dll" come from?

### ISSUE THREAD

**Issue by TechnikEmpire** [falahati/WindowsFirewallHelper#2]
What is the origin of the "Interop.NetFwTypeLib.dll" dll?

**Comment by falahati** [comment]
I actually missed both your responses, sry about that.
"Interop.NetFwTypeLib.dll" is packaged with the library and created by VS as a proxy for "NetFwTypeLib" COM object located within the "FirewallAPI.dll" file at "%WINDIR%\System32".

Read more:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365287(v=vs.85).aspx
