### ISSUE TITLE
How to specify remote IP address

### ISSUE THREAD

**Issue by danucalovj** [falahati/WindowsFirewallHelper#22]
How do you specify a remote IP address as part of the scope of an outbound rule? Example, I want to create a rule for an app that blocks outbound connections to a specific IP address.

**Comment by falahati** [comment]
There is a property for remote addresses (`RemoteAddresses `). Can you share your code as of now?

**Comment by danucalovj** [comment]
Hi falahati, I was able to get this issue resolved by looking at other cases (Issue #11):

Rule.RemoteAddresses = {WindowsFirewallHelper.Addresses.SingleIP.Parse("192.168.0.1)}

Closing issue, and thank you!
