### ISSUE TITLE
There are no more endpoints available from the endpoint mapper. (Exception from HRESULT: 0x800706D9.

### ISSUE THREAD

**Issue by PhyxionNL** [falahati/WindowsFirewallHelper#24]
`at WindowsFirewallHelper.COMInterop.INetFwRules.GetEnumeratorVariant()
at WindowsFirewallHelper.FirewallAPIv2.Firewall.SyncRules() at offset 0
at WindowsFirewallHelper.FirewallAPIv2.Firewall.get_Rules() at offset 6`

In version 1.6.2.36 this is happening on some systems.

**Comment by falahati** [comment]
Is this Windows 7? Probably the Firewall service is disabled or stopped. Using the preview release you can detect these situations. Otherwise, you need to capture the exception and ignore the firewall logic.

**Comment by PhyxionNL** [comment]
Yes, it's indeed on Windows 7, I've so far seen it on Starter and Home Premium (although that probably doesn't matter). I'll capture it for now and await the final of preview version 👍
