### ISSUE TITLE
Please add xml documention for intelligence docs.

### ISSUE THREAD

**Issue by GF-Huang** [falahati/WindowsFirewallHelper#25]
![image](https://user-images.githubusercontent.com/4510984/54465553-acc93c00-47b6-11e9-967f-5a25aa2e38de.png)

Users can not see any doc of classes, methods, fields in your library if you don't check this option.
Also, you have to add the xmls into the nuget package folder that same to dlls.

![image](https://user-images.githubusercontent.com/4510984/54465467-3cbab600-47b6-11e9-9e44-aa094484d626.png)

**Comment by falahati** [comment]
Hah, it was part of the NuGet package in the previous versions. Probably forgot to enable it again after moving to NetCore project. Thanks for reporting this.

**Comment by GF-Huang** [comment]
:)

**Comment by falahati** [comment]
This should be fixed now and the new releases should have these changes.
