### ISSUE TITLE
Sample - Create Port Rule fails

### ISSUE THREAD

**Issue by gregsohl** [falahati/WindowsFirewallHelper#29]
Adding a port rule in the sample Winforms application fails, and I believe would with any call to FirewallManager.Instance.CreatePortRule that includes the protocol. The problem occurs when the Protocol is set to {Any} with the port set. The error received is:

"Port number can only be specified for the UDP and TCP protocols."

However, the protocol isn't set to UDP or TCP before it is set to {Any} by the constructor tree for FirewallWASRuleWin8. The issue is on FirewallWASRule.cs:76, where the protocol is set to {Any} before the Property Initializer in the original constructor call back at FirewallWAS.cs:166 is executed.

**Comment by falahati** [comment]
Thanks for reporting problems with the pre-release version.

This should be fixed in the latest master commit. Will be released with the v2 beta version as soon as I write some tests, double-check the library on WinXP and hopefully catch some bugs here and there.
