### ISSUE TITLE
Modifying remoteaddresses - How to?

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#3]
It is unclear to me how to modify the RemoteAddresses property (or other addresses) for a rule.
For example, I want to add and/or remove remote addresses for an existing rule.

I am able to get a reference to the existing rule I want to modify, however there is no constructor for IAddress, nor any methods that let one modify the address and subsequently assign the array of IAddress  to the rule's RemoteAddresses property.

Ultimately my goal is to simply get a reference to the rule and then apply the new list of RemoteAddresses for the rule.

Your help would be most appreciated.

**Comment by TimesliceTechnologies** [comment]
I resolved my issue as follows:

>          Dim NewIPs As New List(Of IAddress)
            For Each ip In {"192.168.1.1", "192.168.1.200", "201.101.103.104"}
                NewIPs.Add(New WindowsFirewallHelper.Addresses.NetworkAddress(IPAddress.Parse(ip)))
            Next
            Dim v = WindowsFirewallHelper.Addresses.NetworkAddress.TryParse("192.168.2.201", Addresses.NetworkAddress.LocalSubnet)
            objRule.RemoteAddresses = NewIPs.ToArray

**Comment by falahati** [comment]
You can also create a new instance from the `WindowsFirewallHelper.Addresses.SingleIP` class. It does accept a `byte` array and a `long` value for the IP. Or you can convert an `IPAddress` object to `SingleIP` simply by using the `WindowsFirewallHelper.Addresses.SingleIP.FromIPAddress()` static function.

The same thing is true for other classes in this namespace.
