### ISSUE TITLE
Windows Firewall Service requires restart for RDP to work (Details inside)

### ISSUE THREAD

**Issue by aamore** [falahati/WindowsFirewallHelper#31]
Using: **Windows 7 Embedded Standard SP1**

Hey guys, I am trying to get RDP to work correctly. I have opened all the necessary firewall ports and predefined rules in the inbound rules list and enabled all the necessary GPO's and registry items.

For some reason, even though Windows Firewall is set to automatically start, and the service itself says "started," but for the rules to actually apply correctly, restarting the service works and I am able to RDP into the device. 

I have checked msconfig to see if the service is enabled on startup, and it is. 

Any help would be appreciated. Thanks!

**Comment by falahati** [comment]
This is not really in the scope of this project and is more appropriate to be posted on superusers.com.
