### ISSUE TITLE
Version on NuGet not in sync with GitHub

### ISSUE THREAD

**Issue by kpisaksen** [falahati/WindowsFirewallHelper#36]
The source code on GitHub for version 1.6.3.40 includes the bug fix for port range "Must include last element of the range" (https://github.com/falahati/WindowsFirewallHelper/commit/4d8178670ac09cff787b444d86add42bb1a3e51d) for "PortHelper.cs" (https://github.com/falahati/WindowsFirewallHelper/blob/1.6.3.40/WindowsFirewallHelper/Helpers/PortHelper.cs). However, the exact same version on NuGet.org still has this bug and a look at the code in the package confirms this.

It looks like something failed in the pipeline for the PR, but I can´t find the details.

Would it be possible to make a new release that includes the port range fix?

**Comment by falahati** [comment]
Thanks for reporting this. I will take a look.

**Comment by kpisaksen** [comment]
@falahati Is there and ETA on a fix for this one?

**Comment by Casper-Olsen** [comment]
@falahati Any update on this?

**Comment by falahati** [comment]
should be fixed now
