### ISSUE TITLE
How to Modify Existing Entries?

### ISSUE THREAD

**Issue by M-Pixel** [falahati/WindowsFirewallHelper#37]
The readme contains examples of adding and removing entries, but not of modifying existing entries.

Let's say I get an instance of a rule like `var rule = FirewallManager.Instance.Rules.First(x => x.Name == "Foo" && x.Direction == FirewallDirection.Inbound)`.  If I use a setter on that `rule` instance, is that sufficient?  Or do I need to pass it to `FirewallManager.Instance.Rules.Add`?  Or would that create a duplicate of the rule?  Do I need to delete the old one, create a new one, copy the properties over, and add the new one?

**Comment by M-Pixel** [comment]
I experimented with this a bit:

When modifying an existing object, and passing it back to `Add`, I get
```
Unhandled Exception: System.NotSupportedException: This operation is not supported with the passed COM object. ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at WindowsFirewallHelper.COMInterop.INetFwRules.Add(INetFwRule rule)
   at WindowsFirewallHelper.InternalHelpers.Collections.ComCollectionBase`4.Add(TManaged item)
```

When modifying an existing object without passing it back to Add, the changes are not actually applied to the registry.

When creating a new rule with the same name as an existing one, and adding it, duplicates are created.

The only way I've found to successfully modify rules is to copy their values into a new Rule instance, delete to old rule, then add the new rule.  Am I missing something?

**Comment by falahati** [comment]
This library is a wrapper around the Firewall COM API and therefore it acts similar to it.
Modifications should get reflected instantly, however, to add or remove a rule you need to use the `.Rules` property.

If you have a problem with the API or if it doesn't work as expected please post the piece of code you are using so I can reproduce the problem.

**Comment by falahati** [comment]
Also, please specify the version of the library that you are using.

**Comment by ddadkhah** [comment]
I have the same problem for updating an existing firewall rule
Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
I am using the version 2.2.0.86
