### ISSUE TITLE
How to specify "All addresses" instead of specific IP addresses for Rule.RemoteAddresses

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#4]
I resolved my prior issue with respect to creating my array of Iaddress to assign to the rule's allowed remoteaddresses, however I do not see how I can set the RemoteAddresses property to "*" implying all addresses.

Can you elaborate on how to apply the non IP addresses that Windows Firewall supports?
EG: "*", "DNS" etc.?

**Comment by falahati** [comment]
Hey,
Please use `WindowsFirewallHelper.Addresses.SingleIP.Any` to match all addresses.

What do you mean by DNS as IP Address?

**Comment by TimesliceTechnologies** [comment]
Thanks for the quick reply - I'll apply your wise advice.
Here's the documentation from MSDN:
[https://msdn.microsoft.com/en-us/library/windows/desktop/aa365366(v=vs.85).aspx](url)

Remote addresses can be a CSV string of addresses as well as "DefaultGateway", "DHCP","DNS","WINS","LocalSubnet" etc.
Unlikely I would utilize these, but curious on how one might apply these.

It might be nice to simply have a way to pass the CSV string directly rather than the safer method using IAddress array.  Just a thought, and maybe that's actually possible anyway and I haven't found that yet.

Truly appreciate your feedback.
Scott

**Comment by falahati** [comment]
LocalSubnet is achievable using the `WindowsFirewallHelper.Addresses.NetworkAddress.LocalSubnet` static field. For other values, you need to create a class and implement the `IAddress.ToString()` method. I will try to add support for these services in the next couple of hours.

**Comment by TimesliceTechnologies** [comment]
Excellent – Thanks for the quick followup.

I’ll keep my eye on things in case you are able to publish an update.

In the meantime I should be able to move forward…
Thanks,

**Comment by TimesliceTechnologies** [comment]
Hi Soroush,

It appears that class WindowsFirewallHelper.Addresses.SingleIP is “internal” so can’t be accessed from the application / assembly referencing WindowsFirewallHelper.

Not sure if that’s intentional, but it prevents using any methods against the SingleIP class…
Keep me posted…

**Comment by TimesliceTechnologies** [comment]
I have changed the class SingleIP from internal to public sealed to gain access to SingleIP methods in a local build.

I will leave that for you to consider in your next build/release.  I suspect that was your intention originally based on similar classes.

**Comment by falahati** [comment]
Check new release.

There is only one breaking change. `WindowsFirewallHelper.Addresses.NetworkAddress.LocalSubnet` is no longer available. Please use the `new WindowsFirewallHelper.Addresses.LocalSubnet()` class instead.

**Comment by TimesliceTechnologies** [comment]
Excellent - new version looks good.
I'm moving forward with my project now.
Thanks for the quick responses and update!
