### ISSUE TITLE
Remote Machines

### ISSUE THREAD

**Issue by SCLD-AFrey** [falahati/WindowsFirewallHelper#42]
Can you make this work on remote machines also? Or just local? I have searched and cannot figure out how to use on remote.

**Comment by falahati** [comment]
this feature is now part of the repo.
To use it you have to create a direct instance of the `FirewallWPA` or `FirewallLegacy` with the machine name / IP of the device. You probably have to run the application as Domain Admin to be able to do so.

`FirewallManager` helper class automatically returns the local instance of the active firewall.
