### ISSUE TITLE
Firewall profile - block

### ISSUE THREAD

**Issue by alizalevinger** [falahati/WindowsFirewallHelper#43]
How can I block all connections but those that match an Allow rule? Seems like` profile.DefaultInboundAction = FirewallAction.Block ` sets the firewall to block all connections, ignoring any allow rules. I'm looking for the option that matches `Block (default)` - the choice available in Windows Firewall With Advanced Security which blocks all connections except those that match an Allow rule?

**Comment by falahati** [comment]
`profile.DefaultInboundAction` is the right way to do so. Then you have to create an allow role for each acceptable action.
