### ISSUE TITLE
Dialog box "Windows Security Alert". Project selects checkbox "Private networks, such as my home or work network" itself

### ISSUE THREAD

**Issue by bob-byte** [falahati/WindowsFirewallHelper#49]
User will have this dialog if my project is run for the first time:
![image](https://user-images.githubusercontent.com/55748049/134002692-ad54d630-7818-408e-b448-938850ee3b63.png)
How to make my project communicating in private networks without the user's request?
I only have tried to code as in an example:
`var rule = FirewallManager.Instance.CreateApplicationRule(
    @"MyApp Rule",
    FirewallAction.Allow,
    @"C:\MyApp.exe"
);
rule.Direction = FirewallDirection.Outbound;
FirewallManager.Instance.Rules.Add(rule);`
But I get an exception UnauthorizedAccessException in the last row:
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at WindowsFirewallHelper.COMInterop.INetFwRules.Add(INetFwRule rule)
   at WindowsFirewallHelper.Collections.FirewallWASRulesCollection'1.InternalAdd(INetFwRule native)
   at WindowsFirewallHelper.InternalHelpers.Collections.ComCollectionBase'4.Add(TManaged item)

**Comment by falahati** [comment]
you need elevation to be able to add firewall rules
