### ISSUE TITLE
IPV6 problem with new WindowsFirewallHelper.Addresses.NetworkAddress(objIP);

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#5]
Attempting to create new WindowsFirewallHelper.Addresses.NetworkAddress from a System.Net.IPAddress object that is using an IPV6 address of: **2a04:4e42:400::323**
(this is one of the DNS entries for CNN.COM incidentally).

**Example**:
`var systemIP = IPAddress.Parse("2a04:4e42:400::323");
  var fwhelperIP = new WindowsFirewallHelper.Addresses.NetworkAddress(systemIP);`

This throws an error "Addresses of different family can not be used."

I also notice the System.Net.IPAddress object throws a SocketException error when trying to access the .Address property which may be related.

Seems like this should work.  Thoughts?

**Comment by falahati** [comment]
Well, you are doing it wrong; first of all, why using `NetworkAddress` for single IP addresses? You can safely use `SingleIP` class.

I just committed a change to make things easier, but I am not going to release it just yet. Nothing special except some sugar variables and small fixes.

Using `NetworkAddress` you need to mention the subnet mask:
```C#
Addresses.NetworkAddress fwhelperIP;
Addresses.NetworkAddress.TryParse("2a04:4e42:400::323/128", out fwhelperIP);
```
or
```C#
var fwhelperIP = new Addresses.NetworkAddress(IPAddress.Parse("2a04:4e42:400::323"), IPAddress.Parse("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"));
```

However, you should probably use `SingleIP`:
```C#
Addresses.SingleIP.FromIPAddress(IPAddress.Parse("2a04:4e42:400::323"));
```

After the last commit you can also do this:
```C#
Addresses.NetworkAddress fwhelperIP;
Addresses.NetworkAddress.TryParse("2a04:4e42:400::323", out fwhelperIP);
```

or this:
```C#
var fwhelperIP = new Addresses.NetworkAddress(IPAddress.Parse("2a04:4e42:400::323"));
```
