### ISSUE TITLE
Problem creating ICMP rules [Help Wanted] (again!)

### ISSUE THREAD

**Issue by sscotter** [falahati/WindowsFirewallHelper#52]
Hi,

Today I've updated a legacy project from v1.4.6592.8627 to v2.1.4.81

Most of my code continues to work, but I'm unable to suss how to create a rule to allow ICMP.

Back in 2019 in issue #12 you helped me and gave me the following example.

```
Dim Rule = New WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule("NAME2", FirewallAction.Allow, FirewallDirection.Inbound, FirewallProfiles.Domain)
Rule.Protocol = FirewallProtocol.ICMPv4
Rule.RemoteAddresses = {WindowsFirewallHelper.Addresses.SingleIP.Parse("192.168.0.1")}
FirewallManager.Instance.Rules.Add(Rule)
```

I've been unable to find how to replicate this functionality in v2 of your library. I'd be most grateful if you could assist me!

Cheers

Steve

**Comment by falahati** [comment]
The same code should work, you only need to replace `WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule` with `WindowsFirewallHelper.FirewallRules.FirewallWASRule`.

If you are getting an exception after doing so, please report here so that I look deeper into it.

**Comment by sscotter** [comment]
That worked perfectly, thank you!

```
Dim Rule = New WindowsFirewallHelper.FirewallRules.FirewallWASRule("NAME2", FirewallAction.Allow, FirewallDirection.Inbound, FirewallProfiles.Domain)
Rule.Protocol = FirewallProtocol.ICMPv4
Rule.RemoteAddresses = {WindowsFirewallHelper.Addresses.SingleIP.Parse("192.168.0.1")}
FirewallManager.Instance.Rules.Add(Rule)
```
