### ISSUE TITLE
Problems with Assigning IPV6 SingleIP, RemoteAddresses issue with IPV6

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#6]
Thanks for prior issue help.

I am trying to assign a SingleIP IPV6 address to Rule.RemoteAddresses.
Although it appears it may work, at some point when the joined string array is applied in StandardRule.cs to UnderlyingObject.RemoteAddresses something, presumably NetFwTypeLib, changes the single IPV6 address into a range.

For example:
2607:fea8:4260:31a::9
becomes 
2607:fea8:4260:31a::9-2607:fea8:4260:31a::9

This creates a problem when you subsequently try to read and return Rule.RemoteAddresses later because IPRange.parse doesn't recognize the single IP range, and SingleIP also doesn't recognize what appears to be a range.  As a result it simply doesn't get returned in the list of IPaddresses from Rule.RemoteAddresses.

Here's a small console app that should demo the problem more clearly (I hope). Note I am using the latest code you have here as of Nov 24 rather than the released Nuget version which also has some problems with IPV6 you already fixed yesterday.

`using System;
using System.Collections.Generic;
using System.Linq;
using WindowsFirewallHelper;

namespace AddressTest
{
    class Program
    {
        static void Main(string[] args)
        {
            setRemoteAddresss();
            Console.WriteLine("Press any key to end.");
            var c = Console.ReadKey();
        }

        static void setRemoteAddresss()
        {
            var RuleName = "Remote Desktop - User Mode (TCP-In)";
            var objRule = (from obj in FirewallManager.Instance.Rules where obj.Direction == FirewallDirection.Inbound && obj.Name == RuleName orderby obj.Name select obj).FirstOrDefault();

            List<IAddress> NewIPs = new List<IAddress>();
            List<string> iplist = new List<string> { "2607:fea8:4260:31a::9" };

            foreach (var iptext in iplist)
            {
                NewIPs.Add(WindowsFirewallHelper.Addresses.SingleIP.Parse(iptext));
            }

            Console.WriteLine("Assigning these RemoteAddresses:");
            foreach (var objIP in NewIPs)
            {
                Console.WriteLine(objIP.ToString());
            }
            objRule.RemoteAddresses = NewIPs.ToArray();

            Console.WriteLine("RemoteAddresses actually assigned:");
            var assignedIPs = objRule.RemoteAddresses;
            foreach (var objIP in assignedIPs)
            {
                Console.WriteLine(objIP.ToString());
            }

            return;
        }
    }
}
`

**Comment by falahati** [comment]
This was a strange behavior on the Windows Firewall API part. Grab the latest version in which I solved it with correctly identifying IP ranges containing only one IP address as an instance of `SingleIP`.

**Comment by TimesliceTechnologies** [comment]
Excellent - Thanks for the super-fast turnaround.
Have installed and tested and its working great.
