### ISSUE TITLE
Ability to directly get / set the underlying Rule RemoteAddresses and LocalAddresses string

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#7]
Is it possible (or could it be possible) to directly get/set the **underlying** Rule's RemoteAddresses and LocalAddresses properties through WIndowFirewallHelper?

I understand the entire objective is to safely wrap these properties using arrays of IAddress, but it would be nice to be able to get/set the raw string properties if for no other reason than debugging issues like my previously posted issue trying to assign a single IPV6 address.

EG:
`var mystring=objRule.RemoteAddressesString;`
and
`objRule.RemoteAddresses=mystring;
`

**Comment by falahati** [comment]
I just made all rule's `UnderlyingObject`s public. Update your NuGet package. However, you need to figure out the real type of the `IRule` variable before being able to use them.


```C#
if (objRule is WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule)
{
   var mystring = ((WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule) objRule).UnderlyingObject.RemoteAddresses;

   ((WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule) objRule).UnderlyingObject.RemoteAddresses = mystring;
}
```

You might need to make a proxy form the `NetFwTypeLib` COM object (add a reference to the `FirewallAPI.dll` for Windows 7+)

**Comment by TimesliceTechnologies** [comment]
This is most helpful for debugging issues like the recent IPV6 problem.
A little bit cumbersome figuring out the type of the underlying object, but in general this is fine.
Most everything should be done with FirewallHelper rather than directly on the underlying object, but the ability to get a reference to the underlying object is an excellent new capability.
