### ISSUE TITLE
Rule.Name returns unexpected string after assigning to Rule.RemoteAddresses

### ISSUE THREAD

**Issue by TimesliceTechnologies** [falahati/WindowsFirewallHelper#9]
Assume a rule named: "Remote Desktop - User Mode (TCP-In)"

`var objRule = (from obj in FirewallManager.Instance.Rules where obj.Direction == FirewallDirection.Inbound && obj.Name == Default.RuleName orderby obj.Name select obj).FirstOrDefault();`

Before assignment:
objRule.Name == "Remote Desktop - User Mode (TCP-In)"

A list of IPs is assigned: 
objRule.RemoteAddresses=List<IAddress> AddressList;

**Unexpectedly** - Immediately after the assignment :
objRule.Name== **"@FirewallAPI.dll,-28775 "**

Reloading the rule returns the expected name:
` var objRuleRefreshed = (from obj in FirewallManager.Instance.Rules where obj.Direction == FirewallDirection.Inbound && obj.Name == Default.RuleName orderby obj.Name select obj).FirstOrDefault();
`
objRuleRefreshed.Name"Remote Desktop - User Mode (TCP-In)"

This may be an issue with Windows firewall API rather than WindowsFirewallHelper, but it concerns me that subsequent property assignments to the same rule object may fail if the rule's name property has changed for some reason.  I think this bears further examination...

**Comment by falahati** [comment]
Well, it seems like a WindowsFirewall problem as it does resolve resource strings sometimes, but not always.
To make this behavior uniform, I added another layer on top of that to resolve values of string properties for WinRT and STRINGTABLE resources.

Try the latest release.

**Comment by TimesliceTechnologies** [comment]
Fix looks good.  I see you had to do a bit of work to resolve that one.
Clearly there are a few internal issues with the underlying Windows API.
Thanks for looking after that!
